services:
  redis:
    image: redis:8-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rate-limiter-network

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_IP_REQUESTS_PER_SECOND=10
      - RATE_LIMIT_IP_BLOCK_DURATION_SECONDS=300
      - RATE_LIMIT_TOKEN_REQUESTS_PER_SECOND=100
      - RATE_LIMIT_TOKEN_BLOCK_DURATION_SECONDS=600
      - SERVER_PORT=8080
    depends_on:
      - redis
    networks:
      - rate-limiter-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  rate-limiter-network:
    driver: bridge
